[package]
name = "solana-trader-proto"
version = "0.2.10"
edition = "2021"
authors = ["support@bloxroute.com"]
license = "MIT"
description = "A Solana Trader API protocol implementation."
documentation = "https://docs.bloxroute.com/solana/trader-api-v2"
repository = "https://github.com/bloXroute-Labs/solana-trader-proto"
homepage = "https://bloxroute.com/"
readme = "README.md"
keywords = ["solana", "blockchain", "trader", "grpc", "raydium"]
categories = ["api-bindings"]
include = ["**/*.rs", "Cargo.toml", "Cargo.lock", "README.md", "proto"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "rust/lib.rs"

[dependencies]
tonic = "0.14.2"
prost = "0.14.1"
tonic-prost = "0.14.2"
serde = "1.0.214"
serde_derive = "1.0.214"
prost-wkt-types = "0.7.0"
base64 = "0.22.1"
regex = "1.11.1"

[build-dependencies]
tonic-prost-build = "0.14.2"
serde = "1.0.227"
regex = "1.11.3"
